language: python

python:
    - "2.7"

virtualenv:
      system_site_packages: true

before_install:
    - git clone git@github.com:chutsu/playground.git
    - cd playground; python setup.py install; cd -

before_script:
    - sudo apt-get update
    - sudo apt-get install postgresql
    - sudo apt-get install postgresql-client
    - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
    - echo `cat ~/.ssh/id_rsa.pub` > ~/.ssh/authorized_keys
    - createuser -s playground_user
    - createdb -O playground_user playground

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    python tests/unittest_runner.py

branches:
  only:
      - master

notifications:
  recipients:
    - chutsu@gmail.com
  email:
    on_success: change
    on_failure: always
