language: python

python:
    - "2.7"

virtualenv:
      system_site_packages: true

before_install:
     - sudo apt-get install -qq python-numpy python-scipy

install:
    # update and install postgresql
    - sudo apt-get update
    - sudo apt-get install libblas-dev
    - sudo apt-get install libatlas-dev
    - sudo apt-get install liblapack-dev

    # create ssh keys and write them to authorized_keys
    - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
    - echo `cat ~/.ssh/id_rsa.pub` > ~/.ssh/authorized_keys

    # install python packages
    - pip install -r requirements.txt

script:
    - python tests/unittest_runner.py

branches:
  only:
      - master

notifications:
  recipients:
    - chutsu@gmail.com
  email:
    on_success: change
    on_failure: always
