language: python

python:
    - "2.7"

virtualenv:
      system_site_packages: true

install:
    # update and install postgresql
    - sudo apt-get update
    - sudo apt-get install postgresql
    - sudo apt-get install postgresql-client

    # create postgresql user and database
    - createuser -s playground_user
    - createdb -O playground_user playground

    # create ssh keys and write them to authorized_keys
    - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
    - echo `cat ~/.ssh/id_rsa.pub` > ~/.ssh/authorized_keys

    # install playground to system site packages
    - python setup.py install --prefix $PYTHONPATH

    # virtualenv playground requirements
    - pip install -r requirements.txt

script:
    python tests/unittest_runner.py

branches:
  only:
      - master

notifications:
  recipients:
    - chutsu@gmail.com
  email:
    on_success: change
    on_failure: always
