language:
    python

before_script:
    - sudo apt-get update
    - sudo apt-get install postgresql
    - sudo apt-get install postgresql-client
    - sudo adduser playground_user
    - sudo apt-get install python
    - sudo pip install sympy
    - sudo pip install psycopg2

script:
    python tests/unittest_runner.py

branches:
  only:
      - master

notifications:
  recipients:
    - chutsu@gmail.com
  email:
    on_success: change
    on_failure: always
