language: python

python:
    - "2.7"

before_script:
    - sudo apt-get update
    - sudo apt-get install postgresql
    - sudo apt-get install postgresql-client
    - sudo apt-get install python
    - sudo pip-2.7 install sympy
    - sudo pip-2.7 install psycopg2
    - sudo pip-2.7 install flask

script:
    python tests/unittest_runner.py

branches:
  only:
      - master

notifications:
  recipients:
    - chutsu@gmail.com
  email:
    on_success: change
    on_failure: always
